name: icure_dart_sdk
description: icure low level dart sdk.
version: 1.1.2
homepage: https://icure.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: '>=0.13.0 <0.14.0'
  intl: '^0.17.0'
  meta: '^1.7.0'
  tuple: ^2.0.0
  uuid: ^3.0.5
  pointycastle: ^3.5.1
  crypton: ^2.0.3
  steel_crypt: ^3.0.0
  convert: ^3.0.1
  collection: ^1.15.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1
